spring:
  datasource:
    url: jdbc:mysql://localhost:3306/unknown?autoReconnect=false
    username: unknown
    password: unknown
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8090